// response api

// Generated by https://quicktype.io

export interface IStoreResponse {
  ingredients: Ingredient[];
}

export interface Ingredient {
  _id: string;
  name: string;
  qty: number;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

// Generated by https://quicktype.io

export interface IRecipeResponse {
  recipes: Recipe[];
}

export interface Recipe {
  _id: string;
  name: string;
  ingredients: IngredientItem[];
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface IngredientItem {
  _id: string;
  name: string;
  qty: number;
}

// Generated by https://quicktype.io

export interface IShoppingResponse {
  orders: Shopping[];
}

export interface Shopping {
  _id: string;
  ingredient: Ingredient;
  qty: number;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

// Generated by https://quicktype.io

export interface IOrderResponse {
  orders: Order[];
}

export interface Order {
  _id: string;
  name: string;
  ingredients: IngredientItem[];
  status: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}
